version: 2
updates:
  - package-ecosystem: gomod
    directory: /http2/go-grpc
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: gomod
    directory: /http2/go-http2
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: gradle
    directory: /http2/java-grpc
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: gradle
    directory: /http2/java-http2
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: npm
    directory: /http2/node-grpc
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: npm
    directory: /http2/node-http2
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: pip
    directory: /http2/python-grpc
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: pip
    directory: /http2/python-http2
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: bundler
    directory: /http2/ruby-grpc
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: bundler
    directory: /http2/ruby-http2
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Europe/Berlin"
