# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"\t\n\x07Request\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\'\n\x07\x45xample\x12\x1c\n\x03Run\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=26
  _globals['_RESPONSE']._serialized_start=28
  _globals['_RESPONSE']._serialized_end=55
  _globals['_EXAMPLE']._serialized_start=57
  _globals['_EXAMPLE']._serialized_end=96
# @@protoc_insertion_point(module_scope)
