# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("example.proto", :syntax => :proto3) do
    add_message "Request" do
    end
    add_message "Response" do
      optional :message, :string, 1
    end
  end
end

Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Request").msgclass
Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
