# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: example.proto for package ''

require 'grpc'
require './example_pb.rb'

module Example
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Example'

    rpc :Run, ::Request, ::Response
  end

  Stub = Service.rpc_stub_class
end
